$schema: https://json.schemastore.org/github-workflow.json
name: dotnet package

on: [push]

jobs:
  check_formatting:
    runs-on: ubuntu-latest
    name: Check Formatting
    steps:
      - uses: actions/checkout@v2
      - run: |
          dotnet tool restore
          dotnet csharpier --check .
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        working-directory: AutomaticInterface
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
        working-directory: AutomaticInterface
      - name: Test
        run: dotnet test --no-restore --verbosity normal
        working-directory: AutomaticInterface
      - name: Nuget
        if: startsWith(github.ref, 'refs/heads/master')
        run: nuget push **\release\**\AutomaticInterface.*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}